spring:
  application:
    name: virdeanoff-auth-server
  mvc:
    log-request-details: true
    log-resolved-exception: true
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/virdeanoff_db
    username: test
    password: test
  security:
    oauth2:
      authorizationserver:
        issuer: "http://localhost:9191"
debug: true
logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE
server:
  port: 9191